### ISSUE TITLE
Have You Developed it all By your self ?

### ISSUE THREAD

**Issue by Siddhesh2377** [abodinagdat16/Star2D#1]

**Comment by neoapps-dev** [comment]
Yes it was fully developed by Star4Droid and AbodiNadjat (i hope i wrote it write)

**Comment by Siddhesh2377** [comment]
I would love to contribute, if you guys have any group then please add me, I am a Android developer but i work on Android studio

**Comment by abodinagdat16** [comment]
@Siddhesh2377 First... we added some bugs to this project... and you should fix that bugs (as a test for you ) before contributing...(because we don't want beginner developers develop this project)

**Comment by neoapps-dev** [comment]
> @Siddhesh2377 First... we added some bugs to this project... and you should fix that bugs (as a test for you ) before contributing...(because we don't want beginner developers develop this project)

That's good!

**Comment by Siddhesh2377** [comment]
> @Siddhesh2377 First... we added some bugs to this project... and you should fix that bugs (as a test for you ) before contributing...(because we don't want beginner developers develop this project)

i don't have any problems, let me be clear. i can help you guys with ui, and bugs, and may be adding new features

**Comment by Siddhesh2377** [comment]
> @Siddhesh2377 First... we added some bugs to this project... and you should fix that bugs (as a test for you ) before contributing...(because we don't want beginner developers develop this project)

tell me where should i start ?

**Comment by abodinagdat16** [comment]
@Siddhesh2377 first...i added an toast when loading images in the editor ...remove it...as a test for you ... second if you can add gizmo to the game editor 😀 search about it if you didn't know it... but before all make your own fork ....

**Comment by Siddhesh2377** [comment]
Okay

**Comment by Siddhesh2377** [comment]
> @Siddhesh2377 first...i added a toast when loading images in the editor ...remove it...as a test for you ... second if you can add gizmo to the game editor 😀 search about it if you didn't know it... but before all make your own fork ....

did you guys created it in sketchware ?

**Comment by Siddhesh2377** [comment]
hey dude, where did you ask to put the toast, when i pick a img from gallery or when i set it on object ?

**Comment by abodinagdat16** [comment]
@Siddhesh2377 we developed it on code assist but now i converted it to android ide .. as you know you can run it in android studio...

**Comment by abodinagdat16** [comment]
@Siddhesh2377 Did you have facebook ... whatsapp or telegram...

**Comment by Siddhesh2377** [comment]
> @Siddhesh2377 Did you have facebook ... whatsapp or telegram...

I do have telegram: t.me/siddhesh_2377

**Comment by Siddhesh2377** [comment]
> @Siddhesh2377 we developed it on code assist but now i converted it to android ide .. as you know you can run it in android studio...

I saw the dir of android ide, by reading the code i thought you developed it in sketchware

**Comment by Siddhesh2377** [comment]
What is the next task ?
